version: '3'
services:
  database_prod:
    image: "postgres:alpine" # use latest official postgres version
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - database-data-prod:/var/lib/postgresql/data/ # persist data even if container shuts down
  database_dev:
    image: "postgres:alpine" # use latest official postgres version
    env_file:
      - database_dev.env
    ports:
      - 5433:5432
    volumes:
      - database-data-dev:/var/lib/postgresql/data/ # persist data even if container shuts down
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  database-data-prod: # named volumes can be managed easier using docker-compose
  database-data-dev: